### ISSUE TITLE
Sometimes the hidden canvas overlaps the visible canvas

### ISSUE THREAD

**Issue by planger** [eclipsesource/graphical-lsp#118]
This becomes visible when we for instance change the cursor type via css on the sprotty svg element (as done for the tool feedback) and the cursor actually doesn't change in the first ~ 200 vertical pixels of the canvas.

**Comment by planger** [comment]
Spin-off ticket from #115

**Comment by planger** [comment]
I think I found the reason for this issue. Our CSS file misses to import the `sprotty.css`. Instead, our css contains it, but not completely. The following part is missing:
```css
.sprotty-hidden {
    display: block;
    position: absolute;
    width: 0px;
    height: 0px;
}
```

This lead to the sprotty-hidden `div` to actually consume space and therefore eventually interfering with the normal sprotty `div`.
